### ISSUE TITLE
教程中 wxss中的.playlist_container样式，出现的很莫名其妙的问题

### ISSUE THREAD

**Issue by KuMaMon2019s** [xiecheng328/miniprogram#3]
教程中wxml里并没有出现 class=“playlist_container” ，在wxss中指定了.playlist_container，对于小白来说却是有点莫名其妙。于是我用了<view></view>对swiper做了封装。
```html
<view class="playlist_index">
    <view class="index_swiper">
        <swiper indicator-dots="{{true}}" autoplay="{{true}}" interval="5000" duration="500">
            <block wx:for="{{SwiperImgUrls}}">
                <swiper-item >
                    <image src="{{item.url}}" mode="widthFix"/>
                </swiper-item>
            </block>
        </swiper> 
    </view>     
</view>
```

在wxss文件中将wxss重命名为less，并设置样式
```css
.playlist_index{
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
  margin-top: 10rpx;
  flex-direction: row;
}

.index_swiper{
  swiper{
    image{
      width: 100%;
      height: 100%;
    }
  }
}
```
自动生成了代码：
playerlist.wxss：
```css
.playlist_index {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
  margin-top: 10rpx;
  flex-direction: row;
}
.index_swiper swiper image {
  width: 100%;
  height: 100%;
}
```
希望能解决相同困扰的小伙伴
